/*
 * nn_aibro_a.h
 * A pre-trained time-predictable artificial neural network, generated by Keras2C.py.
 * Based on ann.h written by keyan
 */

#ifndef NN_AIBRO_A_H_
#define NN_AIBRO_A_H_

#pragma once

// includes
#include "nn_types.h"

// NOTE: only values marked "*" may be changed with defined behaviour

// Network input defines
#define AIBRO_A_INPUT_DIM_COUNT	1
#define AIBRO_A_INPUT_DIM_0	3

// Network output defines
#define AIBRO_A_MAX_PL_LEN 2
#define AIBRO_A_OUTPUT_DIM_COUNT	1
#define AIBRO_A_OUTPUT_DIM_0	3

// Dense layer defines
#define AIBRO_A_L0_DENSE_NEURON_COUNT	3
#define AIBRO_A_L0_DENSE_USE_BIAS	1
#define AIBRO_A_L0_DENSE_ACTIVATION	ACT_ENUM_TANH	// *
#define AIBRO_A_L0_DENSE_DIM_COUNT	1
#define AIBRO_A_L0_DENSE_DIM_0	3

// Dense layer defines
#define AIBRO_A_L1_DENSE_NEURON_COUNT	3
#define AIBRO_A_L1_DENSE_USE_BIAS	1
#define AIBRO_A_L1_DENSE_ACTIVATION	ACT_ENUM_TANH	// *
#define AIBRO_A_L1_DENSE_DIM_COUNT	1
#define AIBRO_A_L1_DENSE_DIM_0	3

// NN weights struct
typedef struct
{
	// Dense layer unit
	NN_NUM_TYPE aibro_a_l0_dense_weights[AIBRO_A_INPUT_DIM_0][AIBRO_A_L0_DENSE_NEURON_COUNT];
	NN_NUM_TYPE aibro_a_l0_dense_bias[AIBRO_A_L0_DENSE_NEURON_COUNT];
	// Dense layer unit
	NN_NUM_TYPE aibro_a_l1_dense_weights[AIBRO_A_L0_DENSE_DIM_0][AIBRO_A_L1_DENSE_NEURON_COUNT];
	NN_NUM_TYPE aibro_a_l1_dense_bias[AIBRO_A_L1_DENSE_NEURON_COUNT];
} NN_AIBRO_A;

// Static storage
NN_AIBRO_A nn_weights_aibro_a;

// Instance
typedef struct
{
	NN_NUM_TYPE inputs[AIBRO_A_INPUT_DIM_0];
	NN_NUM_TYPE aibro_a_l0_dense_outputs[AIBRO_A_L0_DENSE_DIM_0];
	NN_NUM_TYPE outputs[AIBRO_A_MAX_PL_LEN][AIBRO_A_L1_DENSE_DIM_0];
	

	// Output pipeline
	int pl_index;
} NN_DATA_AIBRO_A;

// Functions
void nn_init_aibro_a();
void run_aibro_a_l0_dense();
void run_aibro_a_l1_dense();

void nn_run_aibro_a(NN_DATA_AIBRO_A *nn_data);

#endif /* NN_AIBRO_A_H_ */