/*
 * nn_aibro_c.h
 * A pre-trained time-predictable artificial neural network, generated by Keras2C.py.
 * Based on ann.h written by keyan
 */

#ifndef NN_AIBRO_C_H_
#define NN_AIBRO_C_H_

#pragma once

// includes
#include "nn_types.h"

// NOTE: only values marked "*" may be changed with defined behaviour

// Network input defines
#define AIBRO_C_INPUT_DIM_COUNT	1
#define AIBRO_C_INPUT_DIM_0	5

// Network output defines
#define AIBRO_C_MAX_PL_LEN 2
#define AIBRO_C_OUTPUT_DIM_COUNT	1
#define AIBRO_C_OUTPUT_DIM_0	2

// Dense layer defines
#define AIBRO_C_L0_DENSE_NEURON_COUNT	4
#define AIBRO_C_L0_DENSE_USE_BIAS	1
#define AIBRO_C_L0_DENSE_ACTIVATION	ACT_ENUM_TANH	// *
#define AIBRO_C_L0_DENSE_DIM_COUNT	1
#define AIBRO_C_L0_DENSE_DIM_0	4

// Dense layer defines
#define AIBRO_C_L1_DENSE_NEURON_COUNT	2
#define AIBRO_C_L1_DENSE_USE_BIAS	1
#define AIBRO_C_L1_DENSE_ACTIVATION	ACT_ENUM_TANH	// *
#define AIBRO_C_L1_DENSE_DIM_COUNT	1
#define AIBRO_C_L1_DENSE_DIM_0	2

// NN weights struct
typedef struct
{
	// Dense layer unit
	NN_NUM_TYPE aibro_c_l0_dense_weights[AIBRO_C_INPUT_DIM_0][AIBRO_C_L0_DENSE_NEURON_COUNT];
	NN_NUM_TYPE aibro_c_l0_dense_bias[AIBRO_C_L0_DENSE_NEURON_COUNT];
	// Dense layer unit
	NN_NUM_TYPE aibro_c_l1_dense_weights[AIBRO_C_L0_DENSE_DIM_0][AIBRO_C_L1_DENSE_NEURON_COUNT];
	NN_NUM_TYPE aibro_c_l1_dense_bias[AIBRO_C_L1_DENSE_NEURON_COUNT];
} NN_AIBRO_C;

// Static storage
NN_AIBRO_C nn_weights_aibro_c;

// Instance
typedef struct
{
	NN_NUM_TYPE inputs[AIBRO_C_INPUT_DIM_0];
	NN_NUM_TYPE aibro_c_l0_dense_outputs[AIBRO_C_L0_DENSE_DIM_0];
	NN_NUM_TYPE outputs[AIBRO_C_MAX_PL_LEN][AIBRO_C_L1_DENSE_DIM_0];
	

	// Output pipeline
	int pl_index;
} NN_DATA_AIBRO_C;

// Functions
void nn_init_aibro_c();
void run_aibro_c_l0_dense();
void run_aibro_c_l1_dense();

void nn_run_aibro_c(NN_DATA_AIBRO_C *nn_data);

#endif /* NN_AIBRO_C_H_ */